import type { Metadata } from "next";
import { Figtree, Manrope } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: "400",
});
const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${figtree.variable} antialiased bg-white`}
      >
        <div className="flex font-[family-name:var(--font-manrope)] bg-white text-black h-screen min-h-screen w-screen overflow-hidden">
          <div className="fixed bottom-0 w-screen p-2 bg-white shadow-2xl border-t border-gray-100 shadow-black/70 left-0 sm:hidden z-50 pb-8 pt-4 flex justify-center">
            <button className="uppercase font-semibold gap-2 text-sm flex items-center justify-center">
              <span className="size-10 bg-black rounded-xl"></span>
              <span className="h-10 bg-black text-white p-4 py-2 flex items-center justify-center">
                Book us
              </span>
              <span className="size-10 bg-black rounded-xl"></span>
            </button>
          </div>
          <main className="flex-1 flex-col flex overflow-hidden">
            <Suspense>{children}</Suspense>
          </main>
        </div>
      </body>
    </html>
  );
}
